github_checks:
  annotations: false
coverage:
  range: auto # for your repo set a rane i..e "80...100"
  status:
    patch:
      default:
        target: 95%
    project:
      default:
        target: 95%
        threshold: 1%